server:
  port: 1299
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: aigou-config-server:1299.com
    prefer-ip-address: true
spring:
#  profiles:
#    active: native #读取本地配置
  application:
    name: AIGOU-CONFIG-SERVER
  cloud:
    config:
      server:
#        native:
#          search-locations: D:/github/aigou-config #本地配置所在的目录
        git:
          uri: https://github.com/aigouchenbo/aigou-config.git
          username: aigouchenbo
          password: chenbo0216